# Generated by Django 5.0.6 on 2024-05-28 01:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_habit_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='habit',
            old_name='name',
            new_name='goal',
        ),
        migrations.RenameField(
            model_name='habit',
            old_name='description',
            new_name='goalDescription',
        ),
        migrations.RemoveField(
            model_name='habit',
            name='points',
        ),
    ]
